# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(777, 864)
        Form.setStyleSheet("background-color: rgb(7, 231, 255);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(150, 10, 321, 80))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 30, 161, 20))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 170, 421, 651))
        self.frame_2.setStyleSheet("\n"
"background-color: rgb(85, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.liste = QtWidgets.QTableWidget(self.frame_2)
        self.liste.setGeometry(QtCore.QRect(20, 10, 381, 611))
        self.liste.setMinimumSize(QtCore.QSize(381, 0))
        self.liste.setObjectName("liste")
        self.liste.setColumnCount(3)
        self.liste.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.liste.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.liste.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.liste.setHorizontalHeaderItem(2, item)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 120, 161, 41))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(440, 130, 20, 701))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_tour = QtWidgets.QPushButton(Form)
        self.pushButton_tour.setGeometry(QtCore.QRect(500, 300, 93, 28))
        self.pushButton_tour.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_tour.setObjectName("pushButton_tour")
        self.pushButton_demarer = QtWidgets.QPushButton(Form)
        self.pushButton_demarer.setGeometry(QtCore.QRect(640, 300, 93, 28))
        self.pushButton_demarer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_demarer.setObjectName("pushButton_demarer")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(590, 140, 61, 41))
        self.label_3.setObjectName("label_3")
        self.compteur = QtWidgets.QLCDNumber(Form)
        self.compteur.setGeometry(QtCore.QRect(490, 190, 251, 81))
        self.compteur.setFrameShadow(QtWidgets.QFrame.Plain)
        self.compteur.setDigitCount(8)
        self.compteur.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.compteur.setObjectName("compteur")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">SPEED RUN </span></p></body></html>"))
        item = self.liste.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Tour"))
        item = self.liste.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Temps au tour"))
        item = self.liste.horizontalHeaderItem(2)
        item.setText(_translate("Form", "temps globale"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; text-decoration: underline;\">LISTES DES SCORES</span></p></body></html>"))
        self.pushButton_tour.setText(_translate("Form", "Tour"))
        self.pushButton_demarer.setText(_translate("Form", "Démarrer"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; text-decoration: underline;\">Temps</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
